@hostname = http://localhost
@port = 8080
 @host = {{hostname}}:{{port}}/api
 @contentType = application/json
@token = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWFucGllcm0iLCJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9NQU5BR0VSIiwiUk9MRV9VU0VSIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hcGkvbG9naW4iLCJleHAiOjE2MzgxMjUzMzF9.9Kn6C4N5e0s5_nQTf3fQoLxlkmKg8EQEAkSBsAMLjiI

## LOGIN USER

POST {{host}}/login
Content-Type: {{contentType}}

{
  "username": "jeanpierm",
  "password": "12345"
}

### GET USERS

GET {{host}}/users
Authorization: {{token}}

### CREATE USER

POST {{host}}/users
Content-Type: {{contentType}}
Authorization: {{token}}

{
  "name": "Emily",
  "email": "emily@gmail.com",
  "username": "emily",
  "password": "12345"
}
